# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# @react-native-firebase requires static frameworks (NOT global use_modular_headers!)
# Global use_modular_headers! breaks UIKit/Hermes on Xcode 16+ (Could not build module UIKit)
$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyApp' do
  use_frameworks! :linkage => :static

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-webrtc', :path => '../node_modules/@videosdk.live/react-native-webrtc'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.build_configurations.each do |build_config|
      build_config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        deployment_target = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if deployment_target.nil? || deployment_target.to_f < 15.1
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
        # Xcode 26: avoid explicit module build failures in Hermes/runtime pods
        build_config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      end
    end

    # Xcode 26+ / Apple Clang: fmt 11.0.2 consteval breaks iOS builds (react-native#55601)
    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'

      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end

    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      patched = content.gsub('# define FMT_USE_CONSTEVAL 1', '# define FMT_USE_CONSTEVAL 0')
      if patched != content
        File.chmod(0o644, fmt_base)
        File.write(fmt_base, patched)
        Pod::UI.puts 'Patched fmt/base.h: FMT_USE_CONSTEVAL=0 for Xcode 26+'.green
      end
    end

    # WebRTC-SDK m125+: FrameCryptionState renamed to RTCFrameCryptorState
    webrtc_cryptor = File.expand_path(
      '../node_modules/@videosdk.live/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCFrameCryptor.m',
      __dir__
    )
    if File.exist?(webrtc_cryptor)
      content = File.read(webrtc_cryptor)
      patched = content
        .gsub('FrameEncryptionState', 'RTCFrameCryptorState')
        .gsub('FrameCryptionState', 'RTCFrameCryptorState')
      if patched != content
        File.chmod(0o644, webrtc_cryptor)
        File.write(webrtc_cryptor, patched)
        Pod::UI.puts 'Patched WebRTCModule+RTCFrameCryptor.m for WebRTC-SDK compatibility'.green
      end
    end
  end
end
